import { useCallback, useEffect, useState } from 'react'
import { Link, useSearchParams } from 'react-router-dom'
import { EmptyState, ErrorNotice, PageHeader, StatusBadge } from '../components/Console'
import { getFinding, getFindingAttempts, getFindings, updateFindingStatus } from '../lib/api'
import { formatDate, pageClass, strategyLabel } from '../lib/presentation'
import type { Finding, FindingAttempt } from '../lib/types'

const PAGE_SIZE = 50
const statuses = ['', 'open', 'inconclusive', 'wont_fix', 'false_positive']
const severities = ['', 'critical', 'high', 'medium', 'low']

function FindingEvidence({ id }: { id: string }) {
  const [finding, setFinding] = useState<Finding | null>(null); const [attempts, setAttempts] = useState<FindingAttempt[]>([]); const [error, setError] = useState<string | null>(null)
  useEffect(() => { Promise.all([getFinding(id), getFindingAttempts(id)]).then(([finding, attempts]) => { setFinding(finding); setAttempts(attempts) }).catch(error => setError(error.message)) }, [id])
  if (error) return <ErrorNotice message={error} />
  if (!finding) return <p className="text-xs text-white/35">Loading evidence…</p>
  return <div className="mt-4 grid lg:grid-cols-2 gap-5 border-t border-white/10 pt-4"><div><h3 className="text-[9px] uppercase tracking-wider text-white/35">Latest evaluator verdict</h3><pre className="mt-2 whitespace-pre-wrap break-words text-[10px] text-white/65">{JSON.stringify(finding.latest_verdict ?? { verdict: 'No verdict recorded' }, null, 2)}</pre></div><div><h3 className="text-[9px] uppercase tracking-wider text-white/35">Contributing attempts · {attempts.length}</h3><div className="mt-2 space-y-2">{attempts.map(attempt => <Link to={`/campaigns/${attempt.run_id}`} key={attempt.id} className="block border border-white/[0.08] p-2 text-[10px] text-white/60 hover:border-white/30">Run {attempt.run_id} · #{attempt.attempt_number} · {strategyLabel(attempt.strategy_type)} · score {attempt.score.toFixed(2)}</Link>)}</div></div></div>
}

function TransitionControl({ finding, onUpdated }: { finding: Finding; onUpdated: () => void }) {
  const [next, setNext] = useState(''); const [reviewer, setReviewer] = useState(''); const [rationale, setRationale] = useState(''); const [error, setError] = useState<string | null>(null); const [saving, setSaving] = useState(false)
  const allowed: Record<string, string[]> = { open: ['inconclusive', 'wont_fix', 'false_positive'], inconclusive: ['open', 'wont_fix', 'false_positive'], wont_fix: [], false_positive: [] }
  if (!allowed[finding.status]?.length) return <span className="text-[10px] text-white/25 uppercase">Terminal lifecycle state</span>
  const requiresRationale = next === 'wont_fix' || next === 'false_positive'
  const submit = async () => { if (!next) return; if (requiresRationale && (!reviewer.trim() || !rationale.trim())) { setError('Reviewer ID and rationale are required for this transition.'); return } setSaving(true); setError(null); try { await updateFindingStatus(finding.finding_id, { status: next, reviewer_id: reviewer.trim() || undefined, rationale: rationale.trim() || undefined }); onUpdated() } catch (error) { setError(error instanceof Error ? error.message : 'Lifecycle update failed.') } finally { setSaving(false) } }
  return <div className="mt-4 border-t border-white/[0.07] pt-4"><div className="flex flex-wrap gap-2"><select value={next} onChange={event => setNext(event.target.value)} className="bg-black border border-white/20 px-2 py-1.5 text-[10px] text-white"><option value="">Transition status…</option>{allowed[finding.status].map(status => <option key={status} value={status}>{status.replace(/_/g, ' ')}</option>)}</select>{requiresRationale && <><input value={reviewer} onChange={event => setReviewer(event.target.value)} placeholder="Reviewer ID" className="bg-black border border-white/20 px-2 py-1.5 text-[10px]" /><input value={rationale} onChange={event => setRationale(event.target.value)} placeholder="Rationale" className="bg-black border border-white/20 px-2 py-1.5 text-[10px] min-w-[200px]" /></>}<button disabled={!next || saving} onClick={submit} className="border border-white/30 px-3 py-1.5 text-[10px] uppercase disabled:opacity-30">{saving ? 'Saving…' : 'Confirm'}</button></div>{error && <p className="mt-2 text-[10px] text-red-400">{error}</p>}</div>
}

export default function FindingsPage() {
  const [search, setSearch] = useSearchParams(); const [findings, setFindings] = useState<Finding[]>([]); const [error, setError] = useState<string | null>(null); const [loading, setLoading] = useState(true); const [expanded, setExpanded] = useState(search.get('finding') ?? '')
  const page = Number(search.get('page') ?? '1') || 1; const severity = search.get('severity') ?? ''; const status = search.get('status') ?? ''; const asi = search.get('asi_class') ?? ''
  const load = useCallback(() => { const query = new URLSearchParams({ page: String(page), page_size: String(PAGE_SIZE) }); if (severity) query.set('severity', severity); if (status) query.set('status', status); if (asi) query.set('asi_class', asi); setLoading(true); getFindings(query).then(setFindings).catch(error => setError(error.message)).finally(() => setLoading(false)) }, [asi, page, severity, status])
  useEffect(load, [load]); const setFilter = (key: string, value: string) => { const next = new URLSearchParams(search); if (value) next.set(key, value); else next.delete(key); next.set('page', '1'); setSearch(next) }; const select = (id: string) => { setExpanded(current => current === id ? '' : id); const next = new URLSearchParams(search); if (id === expanded) next.delete('finding'); else next.set('finding', id); setSearch(next, { replace: true }) }
  return <main className={pageClass}><PageHeader eyebrow="Finding lifecycle" title="Findings" /><section className="px-6 sm:px-10 md:px-16 lg:px-20 py-6 border-b border-white/10 flex flex-wrap gap-3"><label className="text-[10px] text-white/45 uppercase">Severity <select value={severity} onChange={event => setFilter('severity', event.target.value)} className="ml-2 bg-black border border-white/20 p-1 text-white"><option value="">All</option>{severities.slice(1).map(item => <option key={item}>{item}</option>)}</select></label><label className="text-[10px] text-white/45 uppercase">Status <select value={status} onChange={event => setFilter('status', event.target.value)} className="ml-2 bg-black border border-white/20 p-1 text-white"><option value="">All</option>{statuses.slice(1).map(item => <option key={item}>{item}</option>)}</select></label><label className="text-[10px] text-white/45 uppercase">ASI <input value={asi} onChange={event => setFilter('asi_class', event.target.value)} placeholder="ASI01" className="ml-2 bg-black border border-white/20 p-1 text-white w-20" /></label></section><section className="px-6 sm:px-10 md:px-16 lg:px-20 py-8">{error && <ErrorNotice message={error} />}{loading && <EmptyState>Loading findings</EmptyState>}{!loading && !error && !findings.length && <EmptyState>No findings match these filters</EmptyState>}<div className="space-y-3">{findings.map(finding => <article key={finding.finding_id} className="border border-white/10 bg-white/[0.015] p-4"><div className="flex flex-wrap gap-4 items-start justify-between"><button onClick={() => select(finding.finding_id)} className="text-left flex-1"><div className="text-red-400 text-[10px]">{finding.asi_class} · {finding.severity}</div><h2 className="mt-2 text-xs uppercase tracking-wide">{strategyLabel(finding.strategy)}</h2><p className="mt-2 text-[10px] text-white/40 break-all">Target: {finding.target_id}</p></button><StatusBadge status={finding.status} /></div><div className="mt-3 flex flex-wrap gap-5 text-[10px] text-white/40"><span>First seen {formatDate(finding.created_at)}</span><span>{finding.seen_in_runs.length} linked run(s)</span><span>{finding.atlas_technique || 'No ATLAS mapping'}</span></div>{expanded === finding.finding_id && <><FindingEvidence id={finding.finding_id} /><TransitionControl finding={finding} onUpdated={load} /></>}</article>)}</div>{findings.length === PAGE_SIZE && <button onClick={() => { const next = new URLSearchParams(search); next.set('page', String(page + 1)); setSearch(next) }} className="mt-5 border border-white/20 px-4 py-2 text-[10px] uppercase">Next page</button>}</section></main>
}
