

strategist:
  model: qwen.qwen3-coder-480b-a35b-v1:0

attacker:
  model: deepseek.v3-v1:0

evaluator:
  model: qwen.qwen3-coder-480b-a35b-v1:0

reporter:
  model: qwen.qwen3-coder-480b-a35b-v1:0

target:
  model: amazon.nova-pro-v1:0
